% bibus Give me the next bus
%
% [] = bibus()
% 
% HELPTEXT
%
%
% Created: 2009-05-05.
% Copyright (c) 2009, Guillaume Maze (Laboratoire de Physique des Oceans).
% All rights reserved.
% http://codes.guillaumemaze.org

% 
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are met:
% 	* Redistributions of source code must retain the above copyright notice, this list of 
% 	conditions and the following disclaimer.
% 	* Redistributions in binary form must reproduce the above copyright notice, this list 
% 	of conditions and the following disclaimer in the documentation and/or other materials 
% 	provided with the distribution.
% 	* Neither the name of the Laboratoire de Physique des Oceans nor the names of its contributors may be used 
%	to endorse or promote products derived from this software without specific prior 
%	written permission.
%
% THIS SOFTWARE IS PROVIDED BY Guillaume Maze ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, 
% INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
% PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Guillaume Maze BE LIABLE FOR ANY 
% DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
% LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
% BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
% STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
% OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
%

function varargout = bibus(varargin)

method = 1;

switch method
	case 1
		%Liberte = 'StopArea%7C202%7CLibert%E9%7CBrest%7C%7C%7C95195%2C14%7C2398794%2C29%7C416%210%3B414%210%3B413%210%3B412%210%3B415%210%3B411%210%3B417%210%3B';
		%Piccard = 'StopArea%7C516%7CPiccard%7CPlouzan%E9%7C%7C%7C89155%2C00%7C2396159%2C50%7C1056%210%3B1055%210%3B';
		Piccard = 'StopArea%7C513%7CPiccard%7CPlouzan%E9%7C%7C%7C89155%2C00%7C2396159%2C50%7C1055%210%3B1056%210%3B';
		Liberte = 'StopArea%7C193%7CLibert%E9%20S%E9galen%7CBrest%7C%7C%7C95004%2C00%7C2398930%2C00%7C389%210%3B388%210%3B';
					
		if str2num(datestr(now,'HH')) > 12
			% This is the afternoon, we come back home !
			DPoint = Piccard;
			APoint = Liberte;
		else
			% This is the morning, we go to work !
			DPoint = Liberte;
			APoint = Piccard;
		end

		base   = 'http://bibus.prod.navitia.com/navitia/ITI_2_AnswersList.asp?';
		Date   = sprintf('%4s%%7C%2s%%7C%0.0f',datestr(now,'yyyy'),datestr(now,'mm'),str2num(datestr(now,'dd')));
		Time   = sprintf('1%%7C%0.0f%%7C%0.0f',str2num(datestr(now,'HH')),str2num(datestr(now,'MM')));
%		suffix = '&CmbDate=0&Criteria=1%7C%7C&PMR=0&Equipment=&Vehicle=&Mode=%7C1%7CPas%20de%20pr%E9f%E9rences%7C&Extend=&DateFinBases=2009%7C08%7C30&DateMajBases=2009%7C04%7C28';
		suffix = '&CmbDate=0&Criteria=1%7C%7C&PMR=0&Equipment=&Vehicle=&Mode=%7C1%7CPas%20de%20pr%E9f%E9rences%7C&Extend=&DateFinBases=2011%7C09%7C04&DateMajBases=2011%7C03%7C29';
		url = sprintf('%sDPoint=%s&APoint=%s&Date=%s&Time=%s&%s',base,DPoint,APoint,Date,Time,suffix);

		foutput = abspath('~/.bibus.html');
		system(sprintf('wget ''%s'' -q -O %s',url,foutput));
		fid=fopen(foutput);ALL='';
		while 1
		    tline = fgetl(fid);
		    if ~ischar(tline), break, end
			ALL=[ALL tline];
		%    disp(tline)
		end
		fclose(fid);
		%disp(ALL)
		ALL=strrep(ALL,'href="../Navitia_params/','href="http://bibus.prod.navitia.com/Navitia_params/');
		fid=fopen(foutput,'wt');
		fprintf(fid,'%s',ALL);
		fclose(fid);

		web(sprintf('file:%s',foutput), '-browser');


	case 2
		ye = str2num(datestr(now,'yyyy'));
		mo = str2num(datestr(now,'mm'));
		da = str2num(datestr(now,'dd'));
		if strcmp(datestr(now,'ddd'),'Sat') | strcmp(datestr(now,'ddd'),'Sun')
			error('Pas d''horaires pour le week-end !');
		end
		if now < datenum(2009,8,31,0,0,0) | now > datenum(2010,7,4,0,0,0)
			error('Les horaires dont je dispose ne sont plus valide pour aujourd''hui');
		end
		vacances = [datenum(2009,10,25,0,0,0):datenum(2009,11,4,0,0,0) ...
					datenum(2009,12,20,0,0,0):datenum(2010,1,3,0,0,0) ...
					datenum(2010,2,14,0,0,0):datenum(2010,2,18,0,0,0) ...
					datenum(2010,4,11,0,0,0):datenum(2010,4,25,0,0,0)];
					
		% Semaine Vacances Scolaires:			
		if ~isempty(find(vacances==datenum(ye,mo,da,0,0,0)))
			disp('Warning: Horaires de Semaine Vacances Scolaires OUT OF DATE !!!!!!');
			% Brest-Ifremer:
			dir1 = [...
					datenum(ye,mo,da,6,44,0),...
					datenum(ye,mo,da,7,04,0),...
					datenum(ye,mo,da,7,21,0),...
					datenum(ye,mo,da,7,59,0),...
					datenum(ye,mo,da,8,26,0),...
					datenum(ye,mo,da,8,55,0),...
					datenum(ye,mo,da,9,27,0),...
					datenum(ye,mo,da,10,15,0),...
					datenum(ye,mo,da,10,42,0),...
					datenum(ye,mo,da,11,18,0),...
					datenum(ye,mo,da,11,48,0),...
					datenum(ye,mo,da,12,22,0),...
					datenum(ye,mo,da,12,47,0),...
					datenum(ye,mo,da,13,20,0),...
					datenum(ye,mo,da,13,55,0),...
					datenum(ye,mo,da,14,28,0),...
					datenum(ye,mo,da,15,0,0),...
					datenum(ye,mo,da,15,31,0),...
					datenum(ye,mo,da,16,6,0),...
					datenum(ye,mo,da,16,38,0),...
					datenum(ye,mo,da,17,10,0),...
					datenum(ye,mo,da,17,43,0),...
					datenum(ye,mo,da,18,10,0),...
					datenum(ye,mo,da,18,40,0),...
					datenum(ye,mo,da,19,10,0),...
					datenum(ye,mo,da,19,30,0),...
					datenum(ye,mo,da,20,12,0)];
			% Ifremer-Brest:					
			dir2 = [...
					datenum(ye,mo,da,6,44,0),...
					datenum(ye,mo,da,7,4,0),...
					datenum(ye,mo,da,7,21,0),...
					datenum(ye,mo,da,7,59,0),...
					datenum(ye,mo,da,8,24,0),...
					datenum(ye,mo,da,8,43,0),...
					datenum(ye,mo,da,9,25,0),...
					datenum(ye,mo,da,10,10,0),...
					datenum(ye,mo,da,10,39,0),...
					datenum(ye,mo,da,11,11,0),...
					datenum(ye,mo,da,11,43,0),...
					datenum(ye,mo,da,12,23,0),...
					datenum(ye,mo,da,12,51,0),...
					datenum(ye,mo,da,13,22,0),...
					datenum(ye,mo,da,13,51,0),...
					datenum(ye,mo,da,14,29,0),...
					datenum(ye,mo,da,14,58,0),...
					datenum(ye,mo,da,15,32,0),...
					datenum(ye,mo,da,16,3,0),...
					datenum(ye,mo,da,16,36,0),...
					datenum(ye,mo,da,17,14,0),...
					datenum(ye,mo,da,17,48,0),...
					datenum(ye,mo,da,18,19,0),...
					datenum(ye,mo,da,18,51,0),...
					datenum(ye,mo,da,19,22,0),...
					datenum(ye,mo,da,20,9,0),...
					datenum(ye,mo,da,20,42,0)];
		% Semaine Periode Scolaire:	
		else 
			disp('Semaine Periode Scolaire (last update 26/Apr/2010)');
			% Brest-Ifremer:
			dir1 = [...
				datenum(ye,mo,da,6,41,0),...
				datenum(ye,mo,da,7,01,0),...
				datenum(ye,mo,da,7,14,0),...
				datenum(ye,mo,da,7,33,0),...
				datenum(ye,mo,da,8,00,0),...
				datenum(ye,mo,da,8,20,0),...
				datenum(ye,mo,da,8,29,0),...
				datenum(ye,mo,da,9,01,0),...
				datenum(ye,mo,da,9,28,0),...
				datenum(ye,mo,da,10,12,0),...
				datenum(ye,mo,da,10,52,0),...
				datenum(ye,mo,da,11,11,0),...
				datenum(ye,mo,da,11,44,0),...
				datenum(ye,mo,da,12,23,0),...
				datenum(ye,mo,da,12,51,0),...
				datenum(ye,mo,da,13,23,0),...
				datenum(ye,mo,da,13,40,0),...
				datenum(ye,mo,da,14,30,0),...
				datenum(ye,mo,da,15,01,0),...
				datenum(ye,mo,da,15,41,0),...
				datenum(ye,mo,da,16,07,0),...
				datenum(ye,mo,da,16,42,0),...
				datenum(ye,mo,da,16,52,0),...
				datenum(ye,mo,da,17,10,0),...
				datenum(ye,mo,da,17,29,0),...
				datenum(ye,mo,da,17,44,0),...
				datenum(ye,mo,da,18,16,0),...
				datenum(ye,mo,da,18,39,0),...
				datenum(ye,mo,da,19,01,0),...
				datenum(ye,mo,da,19,30,0),...
				datenum(ye,mo,da,20,10,0),...
				datenum(ye,mo,da,20,40,0)];
			% Ifremer-Brest:
			dir2 = [...
				datenum(ye,mo,da,6,32,0),...
				datenum(ye,mo,da,7,16,0),...
				datenum(ye,mo,da,7,25,0),...
				datenum(ye,mo,da,7,58,0),...
				datenum(ye,mo,da,8,25,0),...
				datenum(ye,mo,da,8,53,0),...
				datenum(ye,mo,da,9,08,0),...
				datenum(ye,mo,da,9,45,0),...
				datenum(ye,mo,da,10,10,0),...
				datenum(ye,mo,da,10,40,0),...
				datenum(ye,mo,da,11,13,0),...
				datenum(ye,mo,da,11,43,0),...
				datenum(ye,mo,da,12,20,0),...
				datenum(ye,mo,da,12,36,0),...
				datenum(ye,mo,da,13,21,0),...
				datenum(ye,mo,da,13,57,0),...
				datenum(ye,mo,da,14,21,0),...
				datenum(ye,mo,da,14,56,0),...
				datenum(ye,mo,da,15,20,0),...
				datenum(ye,mo,da,15,33,0),...
				datenum(ye,mo,da,15,57,0),...
				datenum(ye,mo,da,16,32,0),...
				datenum(ye,mo,da,17,00,0),...
				datenum(ye,mo,da,17,23,0),...
				datenum(ye,mo,da,17,45,0),...
				datenum(ye,mo,da,18,29,0),...
				datenum(ye,mo,da,18,45,0),...
				datenum(ye,mo,da,19,10,0),...
				datenum(ye,mo,da,19,30,0),...
				datenum(ye,mo,da,20,12,0)];
		end%if
		
		
		% for id=1:length(dir1)
		% 	disp(sprintf('push @list1, DateTime->new(year => $year, month => $month, day => $day, hour => %i, minute => %i);',...
		% 		str2num(datestr(dir1(id),'HH')),str2num(datestr(dir1(id),'MM'))));
		% end
		% for id=1:length(dir2)
		% 	disp(sprintf('push @list2, DateTime->new(year => $year, month => $month, day => $day, hour => %i, minute => %i);',...
		% 		str2num(datestr(dir2(id),'HH')),str2num(datestr(dir2(id),'MM'))));
		% end		
		
%%% FOR THE IPHONE PAGE:		
%%%		$hours = array("21:40","22:12"); // the bus time
		% disp('From Ifremer to Brest')
		% str = '$hours = array(';
		% for id=1:length(dir2)-1
		% 	str = sprintf('%s"%s",',str,datestr(dir2(id),'HH:MM'));
		% end
		% str = sprintf('%s"%s")',str,datestr(dir2(end),'HH:MM'));
		% disp(str)
		
		% disp('From Brest to Ifremer');
		% str = '$hours = array(';
		% for id=1:length(dir1)-1
		% 	str = sprintf('%s"%s",',str,datestr(dir1(id),'HH:MM'));
		% end
		% str = sprintf('%s"%s")',str,datestr(dir1(end),'HH:MM'));
		% disp(str)
		% return
		
		if str2num(datestr(now,'HH')) > 12
			% This is the afternoon, we come back home !			
			disp('Horaires des prochains bus vers Liberte:');
			d=disp_list(dir2,find(dir2>=now,4));
			if nargin == 1 % Send notification to growl for next bus
				growl(sprintf('Prochain bus a %s',datestr(dir2(find(dir2>=now,1)),'HH:MM')),...
					'Bus vers Brest-Liberte',1);
				addtocrontab(dir2(find(dir2>=now,4)));
			end
		else
			% This is the morning, we go to work !
			disp('Horaires des prochains bus vers Ifremer:');
%			datestr(dir1(find(dir1>=now)))
			d=disp_list(dir1,find(dir1>=now,4));
			if nargin == 1 % Send notification to growl for next bus
				growl(sprintf('Prochain bus a %s',datestr(dir1(find(dir1>=now,1)),'HH:MM')),...
					'Bus vers Ifremer',1)
				addtocrontab(dir1(find(dir1>=now,4)));
			end
		end
	
	case 3
%		http://www.bibus.fr/Navitia.aspx?Depart=picca&Arrivee=segal
		if str2num(datestr(now,'HH')) > 12
			% This is the afternoon, we come back home !
			url = 'http://www.bibus.fr/Navitia.aspx?Depart=picca&Arrivee=segal';
		else
			% This is the morning, we go to work !
			url = 'http://www.bibus.fr/Navitia.aspx?Depart=segal&Arrivee=picca';
		end
		web(url,'-browser');
end  %switch
		
		
	
		
		
end %function

function addtocrontab(dd)
	[status,result] = system('crontab -l | grep -v "no crontab for" > crontab.txt');
	
	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% First we clean previous entries:
	fid = fopen('crontab.txt');ii=0;
    while 1
        tline = fgetl(fid);
        if ~ischar(tline), break, end
		ii = ii + 1;
		if strfind(tline,'# bibus reminder')
	        keep(ii) = 0;
		else 	
			keep(ii) = 1;
		end		
    end
    fclose(fid);
	fid0 = fopen('crontab.txt');ii=0;
	fid1 = fopen('crontab1.txt','wt');
    while 1
        tline = fgetl(fid0);
        if ~ischar(tline), break, end
		ii = ii + 1;
		if keep(ii) == 1
			fprintf(fid1,'%s\n',tline);
		end		
    end
    fclose(fid0);
    fclose(fid1);

	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Then we add the new line:
	fid = fopen('crontab1.txt','a+');
	fseek(fid,0,1);
	dds = dd - 15*1/(24*60);
	
	for id = 1 : length(dd)	
		sticky = '-s';
		prior  = 0;
		mess   = sprintf('Prochain bus a %s',datestr(dd(id),'HH:MM'));
		titl   = 'Attention au prochain bus dans 15mins !';
		command = sprintf('/usr/local/bin/growlnotify %s -p %i --appIcon iCal -m ''%s'' -t ''%s''',sticky,prior,mess,titl);
		tline = sprintf('%i\t%i\t%i\t%i\t*\t%s # bibus reminder',str2num(datestr(dds(id),'MM')),str2num(datestr(dds(id),'HH')),...
				str2num(datestr(dds(id),'dd')),str2num(datestr(dds(id),'mm')),command);	
		fprintf(fid,'%s\n',tline);
	end%for id
    fclose(fid);

	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Install new crontab:
	system('crontab crontab1.txt');
	delete('crontab.txt');
	delete('crontab1.txt');
		
end%function



function d = disp_list(diri,id)
	for ii = 1 : length(id)
		dt = abs(fix(86400*(now-diri(id(ii)))/60));
		if dt > 60
			d = sprintf('%i heure(s) et %i minute(s)',fix(dt/60),rem(dt,60));
		else
			d = sprintf('%i minute(s)',dt);
		end
		disp(sprintf('   %s dans %s',datestr(diri(id(ii)),'HH:MM'),d));
	end
end













